name: example
description: The package provides an input that you can control whether the keyboard will show or not without losing focus, ideal for use with a barcode scanner!
version: 1.0.3
homepage: https://github.com/jelufe/input_with_keyboard_control

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  input_with_keyboard_control: 
    path: ../

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter